version: '3.8'
services:
  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/foodash
      - JWT_SECRET=foodash_jwt_super_secret_key_2024_xK9mP
      - STRIPE_SECRET_KEY=sk_test_YOUR_STRIPE_SECRET_KEY
      - CLIENT_URL=http://3.26.93.92
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
